#!/usr/bin/python

import matplotlib
matplotlib.use('Agg')

import time
import os
import sys
import sqlite3
import matplotlib.pyplot as plt
import numpy
import dateutil

from datetime import datetime
from matplotlib import dates
from matplotlib.dates import DayLocator, DateFormatter

templist = list()			#temperatures
timelist = list()			#dates/times

try:
	conn = sqlite3.connect('/home/pi/sensor_data.sqlite')
	c = conn.cursor()
except sqlite3.error, e:
	print "Error %s:", +e.args[0]
	sys.exit(1)

c.execute("select * from temperature_data order by time asc")

for record in c.fetchall():
	templist.append(record[0])
	timelist.append(datetime.strptime(record[1], "%d/%m/%Y %H:%M"))

formatted_time = dates.date2num(timelist)
form = dates.DateFormatter('%H:%M %d/%m/%Y')

figure = plt.figure(figsize=(20,6))
plt.grid(True)
plt.xticks(rotation =80)
ax = plt.gca()
ax.xaxis.set_major_formatter(form)

plot = figure.add_subplot(111)
plot.set_title('RPi Temperature Sensor Data Over 24h Period')
plot.set_xlabel('Time and Date (HH:MM DD/MM/YYYY)')
plot.set_ylabel('Temperature in Fahrenheit')
plot.autoscale_view(True,True,True)

plot.plot_date(formatted_time, templist, 'o')
plt.savefig("/var/www/graph.png", transparent=True, transparency=0, bbox_inches='tight')

conn.commit()
conn.close()
