#!/usr/bin/python

import matplotlib
matplotlib.use('Agg')

import time
import os
import sys
import sqlite3
import matplotlib.pyplot as plt
import numpy
import dateutil

from datetime import datetime
import matplotlib.dates as mdates

templist = list()			#temperatures
timelist = list()			#dates/times

try:
	conn = sqlite3.connect('/home/pi/sensor_data.sqlite')
	c = conn.cursor()
except sqlite3.error, e:
	print "Error %s:", +e.args[0]
	sys.exit(1)

c.execute("select * from temperature_data order by time asc")

for record in c.fetchall():
	templist.append(record[0])
	timelist.append(record[1])

print templist
print timelist
