#!/usr/bin/python

import sqlite3
import time
import sys
import os
import glob

################################ Get i2c data #############################################

try:
	temp_raw = os.popen('i2cget -y 1 0x41 6 w').read()

except os.error as e:
	print "failed!"
	sys.exit(1)

temp_raw = int(temp_raw,16)		#mess with the number because it is recieved in hex
temp_f = ((temp_raw*0.26)-509.96)	#change it to fahrenheit from raw
round(temp_f,2)

print temp_f

###########################################################################################

############################### Put into SQL Database #####################################

dbname = '/home/pi/sensor_data.sqlite'	#database file

conn = sqlite3.connect(dbname)		#open the sql file
curs=conn.cursor()
			#VV Put the data into the two-field table VV#
curs.execute("insert or replace  into temperature_data values((?), datetime('now'))",(temp_f,))

conn.commit()

conn.close()

###########################################################################################
