#!/usr/bin/python


import sys
import os

################################ Get i2c data #############################################

try:
	temp_raw = os.popen('i2cget -y 1 0x41 6 w').read()

except os.error as e:
	print "failed!"
	sys.exit(1)

temp_raw = int(temp_raw,16)		#mess with the number because it is recieved in hex
temp_f = ((temp_raw*0.26)-509.96)	#change it to fahrenheit from raw

print temp_f

###########################################################################################


